sudo: required
language: php
php:
  - 5.5
  - 5.6
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
    - php: 5.6
      env: MAGENTO_VERSION=magento-mirror-1.7.0.2
    - php: 5.6
      env: MAGENTO_VERSION=magento-mirror-1.8.0.0
    - php: 5.6
      env: MAGENTO_VERSION=magento-mirror-1.8.1.0
    - php: 5.6
      env: MAGENTO_VERSION=magento-mirror-1.9.0.1
env:
  - MAGENTO_VERSION=magento-mirror-1.9.2.2
  - MAGENTO_VERSION=magento-mirror-1.9.1.0
  - MAGENTO_VERSION=magento-mirror-1.9.0.1
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.7.0.2
script:
  - curl -sSL https://raw.githubusercontent.com/schmengler/MageTestStand/master/setup.sh | bash
addons:
  code_climate:
    repo_token: da644f40c75cae9192de730382be15615e71c17dbd95077699db8ab9c5da650d
